# Site settings
# in the templates available like {{ site.myvariable }}.
title: Github Pages Portofolio.
email: susanti.sif18@gmail.com
brand: Susanti
headline: Mahasiswa 
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2020 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: susanti.sif18@gmail.com
phone: +1-800-555-2016

# Tracking
googleAnalitycsID: UA-83933844-1

